// services/cashflow/components/Sidebar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { LayoutDashboard, Users, Receipt, BarChart3, Menu, X, Wallet, FileText, Briefcase, Landmark, LineChart, Search, CreditCard, Gauge, FileBarChart, ShieldCheck, Globe } from "lucide-react";
import { useState } from "react";
import AtlasMark from "./AtlasMark";

const ATLAS_COCKPIT_URL = process.env.NEXT_PUBLIC_ATLAS_URL || "http://localhost:5173";

const navigation = [
    { name: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
    { name: "Clientes", href: "/clientes", icon: Users },
    { name: "Contratos", href: "/contratos", icon: Briefcase },
    { name: "Enterprise P&L", href: "/enterprise/pnl", icon: LineChart },
    { name: "AI Cost Explorer", href: "/enterprise/explorer", icon: Search },
    { name: "Pesquisa & ROI", href: "/enterprise/research", icon: Globe },
    { name: "Billing Plus", href: "/enterprise/billing", icon: CreditCard },
    { name: "Forecast & Alertas", href: "/enterprise/forecast", icon: Gauge },
    { name: "Relatórios IA", href: "/enterprise/reports", icon: FileBarChart },
    { name: "Auditoria", href: "/enterprise/audit", icon: ShieldCheck },
    { name: "Faturas", href: "/faturas", icon: FileText },
    { name: "Despesas", href: "/despesas", icon: Receipt },
    { name: "Fluxo de Caixa", href: "/fluxo-caixa", icon: Wallet },
    { name: "Caixa L2 & Sócios", href: "/socios", icon: Landmark },
    { name: "Relatórios", href: "/relatorios", icon: BarChart3 },
];

export default function Sidebar() {
    const pathname = usePathname();
    const [mobileOpen, setMobileOpen] = useState(false);

    return (
        <>
            {/* Mobile toggle */}
            <button
                onClick={() => setMobileOpen(!mobileOpen)}
                className="mobile-menu-btn"
                style={{
                    position: "fixed", top: 16, left: 16, zIndex: 50,
                    padding: 10, borderRadius: 2,
                    background: "rgba(7,8,12,0.85)", color: "var(--l2-fg-1)",
                    border: "1px solid rgba(79,139,255,0.20)",
                    cursor: "pointer",
                    backdropFilter: "blur(16px) saturate(140%)",
                    boxShadow: "0 0 12px rgba(79,139,255,0.08)",
                    display: "none",
                    transition: "box-shadow 0.25s cubic-bezier(0.22, 1, 0.36, 1)",
                }}
            >
                {mobileOpen ? <X size={20} /> : <Menu size={20} />}
            </button>

            {/* Sidebar — Topographic glassmorphism */}
            <aside className={`sidebar-wrapper ${mobileOpen ? "open" : ""}`}>
                {/* Header — Atlas brand */}
                <div style={{
                    height: 72, display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10,
                    padding: "0 18px",
                    borderBottom: "1px solid var(--l2-hairline)",
                }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                        <AtlasMark size={30} title="ATLAS" />
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 4, minWidth: 0 }}>
                            <h1 style={{
                                fontSize: "1rem", fontWeight: 700, margin: 0, color: "var(--l2-fg-1)",
                                lineHeight: 1, letterSpacing: "0.3em", textTransform: "uppercase",
                                fontFamily: "var(--font-sans)",
                            }}>
                                ATLAS
                            </h1>
                            <span style={{ color: "var(--l2-fg-3)", fontWeight: 400, fontSize: "0.5rem", letterSpacing: "0.3em", textTransform: "uppercase", fontFamily: "var(--font-mono)" }}>
                                CASHFLOW
                            </span>
                        </div>
                    </div>
                    <a
                        href={`${ATLAS_COCKPIT_URL}/cashflow`}
                        target="_top"
                        className="topo-btn topo-btn--muted"
                        style={{
                            padding: "4px 8px",
                            fontSize: 8,
                            letterSpacing: "0.14em",
                            textDecoration: "none",
                            whiteSpace: "nowrap",
                        }}
                    >
                        ← Atlas
                    </a>
                </div>

                {/* Navigation — topo-glow links */}
                <nav data-topo="info" style={{
                    padding: "8px 0",
                    display: "flex", flexDirection: "column", gap: 0, flex: 1,
                    overflowY: "auto", overflowX: "hidden",
                }}>
                    <ul role="list" style={{ listStyle: "none", margin: 0, padding: 0 }}>
                    {navigation.map((item) => {
                        const isActive = pathname === item.href || pathname?.startsWith(item.href + "/");
                        return (
                            <li key={item.name}>
                            <Link
                                href={item.href}
                                onClick={() => setMobileOpen(false)}
                                className={isActive ? "topo-nav-active" : "topo-nav-link"}
                                style={{
                                    position: "relative",
                                    display: "flex", alignItems: "center", gap: 14,
                                    padding: "0 12px",
                                    height: 46,
                                    margin: "2px 8px",
                                    borderRadius: "var(--topo-r-sys)",
                                    textDecoration: "none",
                                    transition: "all 0.25s cubic-bezier(0.22, 1, 0.36, 1)",
                                    whiteSpace: "nowrap",
                                    ...(isActive
                                        ? {
                                            background: "rgba(79,139,255,0.10)",
                                            color: "var(--atlas-celestial)",
                                            boxShadow: "inset 2px 0 0 0 rgba(79,139,255,0.70), 0 0 16px rgba(79,139,255,0.12)",
                                          }
                                        : {
                                            background: "transparent",
                                            color: "var(--l2-fg-3)",
                                          }),
                                }}
                                onMouseEnter={(e) => {
                                    if (!isActive) {
                                        e.currentTarget.style.background = "oklch(1 0 0 / 3%)";
                                        e.currentTarget.style.color = "oklch(0.95 0.01 200)";
                                    }
                                }}
                                onMouseLeave={(e) => {
                                    if (!isActive) {
                                        e.currentTarget.style.background = "transparent";
                                        e.currentTarget.style.color = "oklch(0.50 0.02 200)";
                                    }
                                }}
                            >
                                {/* Active left accent bar — signal-cyan glow */}
                                {isActive && (
                                    <span
                                        aria-hidden
                                        style={{
                                            position: "absolute",
                                            left: -8,
                                            top: "50%",
                                            transform: "translateY(-50%)",
                                            width: 3,
                                            height: 22,
                                            borderRadius: "0 2px 2px 0",
                                            background: "var(--emerald-core)",
                                            boxShadow: "0 0 12px var(--emerald-glow)",
                                        }}
                                    />
                                )}
                                <item.icon size={17} strokeWidth={1.5} color="currentColor" style={{ flexShrink: 0 }} />
                                <span style={{
                                    fontFamily: "var(--font-mono)",
                                    fontSize: 12,
                                    fontWeight: 500,
                                    textTransform: "uppercase",
                                    letterSpacing: "0.16em",
                                }}>
                                    {item.name}
                                </span>
                            </Link>
                            </li>
                        );
                    })}
                    </ul>
                </nav>

                {/* Footer — topo system status */}
                <div style={{
                    padding: "14px 18px",
                    borderTop: "1px solid var(--l2-hairline)",
                    display: "flex", flexDirection: "column", gap: 10,
                }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                        <span aria-hidden style={{
                            width: 7, height: 7, borderRadius: "50%",
                            background: "var(--emerald-core)",
                            boxShadow: "0 0 8px var(--emerald-glow)",
                            animation: "topo-glow-pulse 3s ease-in-out infinite",
                        }} />
                        <span style={{
                            fontFamily: "var(--font-mono)", fontSize: 10, textTransform: "uppercase",
                            letterSpacing: "0.16em", color: "var(--emerald-core)"
                        }}>
                            SERVER · ONLINE
                        </span>
                    </div>
                    <div style={{ display: "flex", alignItems: "center", gap: 6, color: "var(--l2-fg-3)" }}>
                        <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="var(--atlas-bronze)" strokeWidth="3" strokeLinecap="square">
                            <path d="M5 5 V19 H13 M15 5 H19 V11 H15 V19 H19" />
                        </svg>
                        <span style={{ fontFamily: "var(--font-mono)", fontSize: 9, letterSpacing: "0.22em", textTransform: "uppercase" }}>
                            BY L2 SYSTEMS
                        </span>
                    </div>
                </div>
            </aside>

            {/* Mobile overlay */}
            {mobileOpen && (
                <div
                    style={{ position: "fixed", inset: 0, zIndex: 30, background: "rgba(0,0,0,0.6)", backdropFilter: "blur(4px)" }}
                    onClick={() => setMobileOpen(false)}
                />
            )}

            {/* Responsive styles handled by globals.css media query */}
        </>
    );
}

// services/web-ui/src/lib/components/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { ChevronLeft, ChevronRight } from '@lucide/svelte';
	import { onMount, onDestroy } from 'svelte';
	import { cockpitModules } from '$lib/modules.js';
	import { checkHealth } from '$lib/api.js';
	import { sidebar, SIDEBAR_WIDTH_COLLAPSED, SIDEBAR_WIDTH_EXPANDED } from '$lib/ui-state.svelte.js';
	import AtlasMark from '$lib/brand/AtlasMark.svelte';

	// ── Collapse state (shared with +layout so main content shifts) ──────────
	onMount(() => {
		const saved = localStorage.getItem('atlas-sidebar-expanded');
		if (saved !== null) sidebar.expanded = saved === 'true';
	});

	function toggleExpanded(): void {
		sidebar.expanded = !sidebar.expanded;
		localStorage.setItem('atlas-sidebar-expanded', String(sidebar.expanded));
	}

	const expanded = $derived(sidebar.expanded);
	const width = $derived(expanded ? SIDEBAR_WIDTH_EXPANDED : SIDEBAR_WIDTH_COLLAPSED);

	// ── Gateway health ────────────────────────────────────────────────────────
	let gatewayOnline = $state<boolean | null>(null);

	async function pollHealth(): Promise<void> {
		try {
			await checkHealth();
			gatewayOnline = true;
		} catch {
			gatewayOnline = false;
		}
	}

	let healthInterval: ReturnType<typeof setInterval> | null = null;

	onMount(() => {
		void pollHealth();
		healthInterval = setInterval(() => void pollHealth(), 30_000);
	});

	onDestroy(() => {
		if (healthInterval !== null) clearInterval(healthInterval);
	});

	// ── Active route detection ────────────────────────────────────────────────
	function isActive(route: string): boolean {
		return $page.url.pathname.startsWith(route);
	}

	const statusColor = $derived(
		gatewayOnline === true ? 'var(--l2-success)' : gatewayOnline === false ? 'var(--l2-error)' : 'var(--l2-fg-3)'
	);
	const statusTopo = $derived(gatewayOnline === true ? 'good' : gatewayOnline === false ? 'bad' : 'atlas');
</script>

<nav
	aria-label="Main navigation"
	data-topo="atlas"
	style="
		position: fixed;
		top: 0;
		left: 0;
		bottom: 0;
		width: {width}px;
		background: linear-gradient(180deg, rgba(10,10,12,0.82), rgba(5,5,7,0.92));
		backdrop-filter: blur(14px) saturate(1.3);
		display: flex;
		flex-direction: column;
		border-right: 1px solid var(--l2-glass-border-lo);
		box-shadow: 1px 0 0 rgba(0,0,0,0.6), 8px 0 32px rgba(0,0,0,0.45);
		transition: width var(--l2-duration-sm) var(--l2-ease);
		z-index: 100;
		overflow: hidden;
	"
>
	<!-- ── Brand header — ATLAS-forward ────────────────────────────────────── -->
	<a
		href="/"
		aria-label="ATLAS home"
		style="
			display: flex;
			align-items: center;
			gap: 12px;
			height: 72px;
			padding: 0 {expanded ? '18px' : '0'};
			justify-content: {expanded ? 'flex-start' : 'center'};
			text-decoration: none;
			border-bottom: 1px solid var(--l2-glass-border-lo);
			flex: none;
		"
	>
		<AtlasMark variant="borne" tone="color" size={30} />
		{#if expanded}
			<div style="display:flex; flex-direction:column; gap:3px; min-width:0;">
				<span
					style="
						font-family: var(--l2-font-display);
						font-weight: 700;
						font-size: 18px;
						letter-spacing: 0.26em;
						line-height: 1;
						color: var(--l2-fg-1);
						white-space: nowrap;
					"
				>ATL<span style="color: var(--atlas-bronze);">A</span>S</span>
				<span
					style="
						font-family: var(--l2-font-mono);
						font-size: 8px;
						letter-spacing: 0.28em;
						text-transform: uppercase;
						color: var(--l2-fg-3);
						white-space: nowrap;
					"
				>OPERATOR COCKPIT</span>
			</div>
		{/if}
	</a>

	<!-- ── Collapse toggle ─────────────────────────────────────────────────── -->
	<button
		onclick={toggleExpanded}
		aria-label={expanded ? 'Collapse sidebar' : 'Expand sidebar'}
		style="
			display: flex;
			align-items: center;
			justify-content: {expanded ? 'flex-end' : 'center'};
			width: 100%;
			height: 34px;
			padding: {expanded ? '0 18px' : '0'};
			background: none;
			border: none;
			border-bottom: 1px solid var(--l2-glass-border-lo);
			cursor: pointer;
			color: var(--l2-fg-3);
			transition: color var(--l2-duration-xs) var(--l2-ease);
		"
		onmouseenter={(e) => { (e.currentTarget as HTMLButtonElement).style.color = 'var(--l2-cyber-blue)'; }}
		onmouseleave={(e) => { (e.currentTarget as HTMLButtonElement).style.color = 'var(--l2-fg-3)'; }}
	>
		{#if expanded}
			<ChevronLeft size={15} strokeWidth={1.5} />
		{:else}
			<ChevronRight size={15} strokeWidth={1.5} />
		{/if}
	</button>

	<!-- ── Navigation ──────────────────────────────────────────────────────── -->
	<ul role="list" style="flex: 1; list-style: none; margin: 0; padding: 10px 0;">
		{#each cockpitModules as mod (mod.id)}
			{@const active = isActive(mod.route)}
			<li>
				<a
					href={mod.route}
					data-topo={active ? 'info' : 'atlas'}
					aria-label={expanded ? undefined : mod.ariaLabel}
					aria-current={active ? 'page' : undefined}
					style="
						position: relative;
						display: flex;
						align-items: center;
						gap: {expanded ? '14px' : '0'};
						justify-content: {expanded ? 'flex-start' : 'center'};
						height: 46px;
						margin: 2px 8px;
						padding: {expanded ? '0 12px' : '0'};
						border-radius: var(--l2-radius);
						text-decoration: none;
						background: {active ? 'rgba(0,240,255,0.07)' : 'transparent'};
						color: {active ? 'var(--l2-cyber-blue)' : 'var(--l2-fg-3)'};
						box-shadow: {active ? 'inset 0 0 0 1px rgba(0,240,255,0.18)' : 'none'};
						transition: background var(--l2-duration-xs) var(--l2-ease), color var(--l2-duration-xs) var(--l2-ease);
					"
					onmouseenter={(e) => {
						if (!active) {
							const el = e.currentTarget as HTMLAnchorElement;
							el.style.background = 'var(--l2-glass-bg-lo)';
							el.style.color = 'var(--l2-fg-1)';
						}
					}}
					onmouseleave={(e) => {
						if (!active) {
							const el = e.currentTarget as HTMLAnchorElement;
							el.style.background = 'transparent';
							el.style.color = 'var(--l2-fg-3)';
						}
					}}
				>
					{#if active}
						<span
							aria-hidden="true"
							style="position:absolute; left:-8px; top:50%; transform:translateY(-50%); width:3px; height:22px; border-radius:0 2px 2px 0; background:var(--l2-cyber-blue); box-shadow:0 0 12px var(--l2-cyber-blue-glow);"
						></span>
					{/if}
					<mod.icon size={expanded ? 17 : 20} strokeWidth={1.5} color="currentColor" />
					{#if expanded}
						<span
							style="
								font-family: var(--l2-font-mono);
								font-size: 12px;
								font-weight: 500;
								text-transform: uppercase;
								letter-spacing: 0.16em;
								white-space: nowrap;
							"
						>{mod.label}</span>
					{/if}
				</a>
			</li>
		{/each}
	</ul>

	<!-- ── Footer — gateway status + L2 endorsement ────────────────────────── -->
	<div
		style="
			padding: {expanded ? '14px 18px' : '14px 0'};
			border-top: 1px solid var(--l2-glass-border-lo);
			display: flex;
			flex-direction: column;
			gap: 10px;
			align-items: {expanded ? 'stretch' : 'center'};
			flex: none;
		"
		data-topo={statusTopo}
	>
		<!-- Gateway status -->
		<div style="display:flex; align-items:center; gap:8px; justify-content:{expanded ? 'flex-start' : 'center'};">
			<span
				aria-hidden="true"
				style="width:7px; height:7px; border-radius:50%; background:{statusColor}; box-shadow:0 0 8px {statusColor}; flex:none;"
			></span>
			{#if expanded}
				<span
					style="font-family:var(--l2-font-mono); font-size:10px; text-transform:uppercase; letter-spacing:0.16em; color:{statusColor};"
				>
					{#if gatewayOnline === true}GATEWAY · ONLINE{:else if gatewayOnline === false}GATEWAY · OFFLINE{:else}GATEWAY · CHECKING{/if}
				</span>
			{/if}
		</div>

		{#if expanded}
			<!-- L2 endorsement (ATLAS-forward, L2-endorsed) -->
			<div style="display:flex; align-items:center; gap:6px; color:var(--l2-fg-3);">
				<svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="var(--l2-fg-2)" stroke-width="3" stroke-linecap="square" aria-hidden="true">
					<path d="M5 5 V19 H13 M15 5 H19 V11 H15 V19 H19" />
				</svg>
				<span style="font-family:var(--l2-font-mono); font-size:9px; letter-spacing:0.22em; text-transform:uppercase;">BY L2 SYSTEMS</span>
			</div>
		{/if}
	</div>
</nav>
